### ISSUE TITLE
External storage using document provider

### ISSUE THREAD

**Issue by avi312singh** [marzika/Snapprefs#101]
In the new version folder to save snaps, stories and all media should be picked using android documentProvider storage, however must be on minimum android 5.0 to use this. This is a way to save stuff on external SD card for OS such as marshmallow.

**Comment by krugm0f0** [comment]
I think this also should apply to custom filter location. It's fixed at /sdcard/Snapprefs/Filters.

**Comment by marzika** [comment]
What you mainly don't understand that I am using an external library for selecting directories. I don't have any way to change it's inner works. Secondly, I will not write my own implementation of directory selection, because it does not worth my time (less than 5% of M+ people use external SDCards). Thirdly, custom filter locations will not be added. it was added and will not be added back because of how the store work and other functions work (not to mention that people fucked up their external and internal storage's permission rendering almost 90% of the functions useless).

If you have a hard time managing your space on your sdcard use apps that move these folders to the external sdcard once in a while.
