### ISSUE TITLE
[REQUEST] Remove Annoyances

### ISSUE THREAD

**Issue by ghost** [marzika/Snapprefs#116]
Is it possible to block the ads that appear between stories?

Also can you please make an option to completely hide the sponsored and live stories from the stories page?

**Comment by marzika** [comment]
I don't have ads inbetween stories, so I cannot check them.
Hiding them are already in the app.

**Comment by ghost** [comment]
The latest version has ads, so you might need to update

**Comment by marzika** [comment]
I am using 9.35.1.0, no ads here.

**Comment by krugm0f0** [comment]
Will latest SP work with SC 9.35.1.0?

**Comment by razorsoup** [comment]
I just had an ad between stories on Snapchat 9.31.1. I assume Snapprefs isn't adding that in (it isn't, right?) so I'm guessing Snapchat is. Today was the first time I've seen one so it seems to be fairly rare.

Edit: Here we go, an article talking about the addition of ads between stories.
http://thenextweb.com/apps/2016/06/13/snapchat-getting-ton-new-ads-thank-new-api/
If you Google "snapchat ads between stories" you'll find a bunch of stories confirming the behavior from around June 13&14 of this year. 

Since you're not currently seeing the ads, what can we provide to help you add the possibility of hiding them?
