### ISSUE TITLE
Major Cache ussage

### ISSUE THREAD

**Issue by TehMerkMods** [marzika/Snapprefs#120]
After around two days of using Snapprefs it begins crashing my snapchat until cache is reset
Just a tip(dont got logs to back this up but yeah next time ill provide some)

**Comment by marzika** [comment]
Without the logcat of the crash I don't know what might cause this.

**Comment by marzika** [comment]
I looked into the cache of the Snapchat app and searched for my cache usage. From the initial app opening Snapchat by itself downloads 80mbs of content, mainly Discover data, multiply it by a few days and you get your massive cache issue. Also, I once again made sure that I don't use any cache.

The problem is unrelated to Snapprefs.
