### ISSUE TITLE
ETA For Snapprefs?

### ISSUE THREAD

**Issue by Abbasoo** [marzika/Snapprefs#130]
I've been waiting since 25/12 !
Can you give us ETA ?

**Comment by vaaski** [comment]
Please get banned.

**Comment by rebane2001** [comment]
Marzika has said it, don't ask for an ETA

But looking at it, it's mostly bugfixes, so it should not be so far away

**Comment by SlayaMods** [comment]
Don't even bother asking you wI'll never get a straight answer

**Comment by krugm0f0** [comment]
Compile the apk yourself if you need it so badly. This is not the place to ask for ETA. 
4. aug. 2016 16.41 skrev SlayaMods notifications@github.com:Don't even bother asking you wI'll never get a straight answer

**Comment by Abbasoo** [comment]
@krugm0f0 How to compile it ?

**Comment by SlayaMods** [comment]
@abbsoo you compile it by using android tools

**Comment by Abbasoo** [comment]
@SlayaMods i know. but how ? can u give instruction ?

**Comment by avi312singh** [comment]
How is this an issue?!?!?

**Comment by SlayaMods** [comment]
@Abbasoo all you need to do is go to build ando build Apk and that's all you have to do

**Comment by rebane2001** [comment]
Ok, so here is the basic step-by-step process:
1. Download and install Android Tools
2. Download the latest SDK stuff using the downloader in the Android Tools (I'm not sure if this is required)
3. Download this project as a zip (or use the GitHub program to auto-sync it)
4. Open the project you downloaded in Android Studio (Android Studio is part of the Tools package)
5. Build it by clicking on "Build" above, then select "Build APK"
6. In the log below, you'll see a link to the APK
7. Uninstall Snapprefs from your phone if you have it (IMPORTANT, else it won't install because of some signature stuff)
8. Install the APK on the phone
9. Enjoy (the bugs?)

**Comment by SlayaMods** [comment]
If you have lucky patcher you can skip the unistall part because it allows you to install apps with different signatures

**Comment by krugm0f0** [comment]
This is probably not for you... 
4. aug. 2016 17.21 skrev SlayaMods notifications@github.com:If you have lucky patcher you can skip the unistall part because it allows you to install apps with different signatures

**Comment by rebane2001** [comment]
Maybe somebody can close this thread now?

**Comment by NightMean** [comment]
Github is not forum... Go on reddit. Please someone close this
