### ISSUE TITLE
[BUG]Landscape & Video

### ISSUE THREAD

**Issue by TehMerkMods** [marzika/Snapprefs#226]
Visual filters do not work on video from what i see 

and 

The Text customise doesn't show in landscape mode :)

**Comment by M1kep** [comment]
We have recently pushed the development branch over to the stable branch in this we have resolved many issue, and added new functionalities. For the time being this build can be downloaded from: http://138.68.21.49:8080/job/SNAPPREFS%20-%20Official%20-%20stable/lastSuccessfulBuild/

**Please Note** This Version Is Built For SnapChat 9.39.5 **End Note**
If you cannot install this version as an update we recomend that you re-install this version. 

If this new build solves your issue please comment, and close the issue. Otherwise leave a comment stating this issue is still present.

**Comment by marzika** [comment]
The visual filters cannot be applied to videos as they are done in Snapchat's native libs.
As for the landscape mode, unfortunately due to the limitation of Xposed right now we cannot Override a needed method to fix this bug.
