### ISSUE TITLE
[Bug] Snapprefs crashing after cancelling pic share via button above camera button on SC

### ISSUE THREAD

**Issue by SilverSix** [marzika/Snapprefs#261]
Sometimes, when trying to take a pic, I press the share button above the circle button on SC, and when I back out of it via the back button or "Cancel" SP crashes, and SC freezes until SP is force closed. This doesn't stop SP from working when SC comes to its senses.

Not sure how to obtain a Logcat for the issue. Downloaded aLogcat and left it open while replicating the issue but nothing is logged.

SC 9.31.1.0
SP 2.0.0
Device: Samsung Galaxy S3 Virgin Mobile
OS: Exodus 10/08/2016 nightly
Android: 6.0.1

**Comment by M1kep** [comment]
@silversix download cat log, open it, click the circles x on the top right to clear the log, open snapchat, cause the freeze, then open catlog, search for snap, click the three vertical dots button on the bottom right, click save, upload here

**Comment by SilverSix** [comment]
I think I got it:
[Snapprefs.txt](https://github.com/marzika/Snapprefs/files/518079/Snapprefs.txt)

**Comment by MrMikeTyson** [comment]
I have the same problem, snapchat crash when i take a picture, filtered logcat is here  
[Log_2016-10-13_21-02-58.txt](https://github.com/marzika/Snapprefs/files/529174/Log_2016-10-13_21-02-58.txt)

**Comment by M1kep** [comment]
We have recently pushed the development branch over to the stable branch in this we have resolved many issue, and added new functionalities. For the time being this build can be downloaded from: http://138.68.21.49:8080/job/SNAPPREFS%20-%20Official%20-%20stable/lastSuccessfulBuild/

**Please Note** This Version Is Built For SnapChat 9.39.5 **End Note**
If you cannot install this version as an update we recomend that you re-install this version. 

If this new build solves your issue please comment, and close the issue. Otherwise leave a comment stating this issue is still present.

**Comment by marzika** [comment]
The issue in your log has been resolved earlier.
