### ISSUE TITLE
Snapchat blocked rooted users!

### ISSUE THREAD

**Issue by Abbasoo** [marzika/Snapprefs#269]
I Changed from Android to iPhone 7 Plus
Fuck you @marzika for this non-working snapprefs _!_

**Comment by Abbasoo** [comment]
I use Snapchat++. It's WORKING with the LATEST VERSION without any problem 010

**Comment by M1kep** [comment]
Ok let's get somethings straight:
1. Snapprefs is for Android
2. Snapchat++ is for ios
3. IPhone != Android
4. Snapchat blocks root. That's outside the scope of Snapprefs
5. You can't root and iPhone

So before you go flinging accusations get your shit right.

Also I hope your trolling....  Otherwise I honestly feel bad for you.

**Comment by marzika** [comment]
Well, the module isn't aimed for people who are
1) not developers
2) not capable of reading and understanding basic concepts of the Android OS
3) below 12 years of age.
Therefore I am glad you don't belong to the userbase.

Snapprefs has never even attempted to bypass the SafetyNet detections, as it is only a simple Xposed module, uncapable of doing such. It's like blaiming a driver, because a car company decided to do some measures that you don't like.

https://m.reddit.com/r/xposed/comments/4mexvu/request_bypass_snapchats_root_detection/
