### ISSUE TITLE
Another version Snapprefs'

### ISSUE THREAD

**Issue by sami0596** [marzika/Snapprefs#289]
Okay.. since Snapchat 9.21.1.0 don't working anymore, I updated snapchat (9.31.1.0) and snapprefs (2.0.0 beta).
The problem is that my snapchat keep crashing after I installed snapprefs.
My question is, if there can be made like a another version of snapprefs, 
where the features is only: custom stickers,  snap/story saving and sharing from gallery and maybe also custom filters..
and if possible... Then make it for the latest working snapchat version ( 9.41.0.0)

If not, then can I get the source code for these features..?

**Comment by NightMean** [comment]
Snapprefs can be only maded for certain version of snapchat current stable is for 9.31.1.0 (beta 2.0.0) there is new version coming with new features which have support for SP 9.39.5.0 (No lower version or higher!)

**Comment by sami0596** [comment]
Did you understand my question? lol

**Comment by NightMean** [comment]
Ah sorry I missreaded a little :/ 
Well to fix the crashing try to post logs from crash and if you are using magisk there are few problems with it.So use normal xposed if u are not using it. For the Few features only snapprefs I think it's pointless because the features can be turned on or off.
For the source code well you are on github there is only source code for the app :D

**Comment by AmineI** [comment]
You basically want a minimalist Snapprefs version right ? 

Also, you're crashing on 2.0.0 beta apparently, which Android version are you using ?

**Comment by KennyTK** [comment]
+1 to minimalist snapprefs on a newer version.

**Comment by sami0596** [comment]
Aminel, Yes..
I am on KitKat version (4.4.2)

**Comment by AmineI** [comment]
Honestly you could just disable every other features in the settings, it's going to make more works to the dev for nothing

About that crash, I think it's because you're on Android 4.x , which is not officially supported anymore.. Can you send a crash log made with Android studio, filtered to show only snapchat's logs, anyway ?

**Comment by sami0596** [comment]
After I updated snapprefs and snapchat, it is working now..
https://github.com/marzika/Snapprefs/issues/290

**Comment by AmineI** [comment]
So you're using 9.39.5.0 right ? It's not over yet, try to take a picture or open a private snap (not story), does it crash ?

**Comment by sami0596** [comment]
It foes even crash anymore after I updatedid it

**Comment by sami0596** [comment]
It does  even not**

**Comment by marzika** [comment]
No other version will be released other than the main one.
