### ISSUE TITLE
Update for snapchat 9.24

### ISSUE THREAD

**Issue by vdeville** [marzika/Snapprefs#49]
Hello new version of snapchat  is not compatible with snappref . Have you idea to fix this ?
If you need help tell me.
Thank.

**Comment by NightMean** [comment]
Yes,new version it's in development... Please check xda for more info and don't ask for ETA like everyone does :P

**Comment by MyTheValentinus** [comment]
Yes sorry friend ! I'm with you !

Valentin Deville
06.01.95.84.37
contact@valentin-deville.eu
http://www.valentin-deville.eu

**Comment by JesusBass** [comment]
Hey man, I'm searching but i can't find the snapprefs link, can you two please help me?

**Comment by joexn** [comment]
You mean this? http://forum.xda-developers.com/xposed/modules/app-snapprefs-ultimate-snapchat-utility-t2947254

**Comment by JesusBass** [comment]
That's foe the snapchat 9.21, and they said update for the 9.24, that's why I'm asking, where's the update for the 9.24? I don't see it :(

**Comment by joexn** [comment]
That's the official thread for snapprefs, people have been commenting on it asking when it'll be updated and some people are getting annoyed. They have said that it'll be ready when the creator has finished his exams and whatnot. There has been many updates to Snapchat since the last release and it can be hard to find all the moderations to the code. - Due to people commenting, they have closed he forum until the next update is released. No one knows when it's coming but it is in development.
