### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by timbremer** [marzika/Snapprefs#6]
Hey, unfortunately we can't use old snapchat versions anymore. Is there any possibility that we could get an update soon?

**Comment by eschriek** [comment]
You could help the developer by decompiling snapchat yourself and look for changes :)

**Comment by Cryptoc1** [comment]
How exactly would one do so? I would totally be willing to help if I knew what to look for.

**Comment by eschriek** [comment]
Well, as you know Xposed is used to hook methods, right?
If you look at the source code of Snapprefs you encounter a list of classes and methods which are of interest to Snapprefs (and will be hooked). 
Let's take ReceivedSnap.getImageBitmap(Context) as example;
When you decompile the snapchat apk and open the ReceivedSnap class you will notice that methods have received names like a,b,c etc. Since we are looking for a method which takes Context as parameter and returns a bitmap you need to find out which method this is, it could be for example a.

Whenever Snapchat releases an update it might change it's classes, so that the previously found class a has now become b.
So, making Snapprefs compatible with the current version of Snapchat is finding the right methods to hook since they have probably been changed.

I typed this very fast, so it might be vague. I don't have time to write a guide nor am I an "expert" with xposed.
If you have basic knowledge of programming in general and take some time to read stuff or find out how things work, you should be able to be of help imo. Besides that is figuring how something works great, it is fun and you learn a lot by doing it, but that's just my opinion :)

Good luck!

**Comment by marzika** [comment]
In versions above 9.3.1.0, the main classes, which held every info of a snap, rendered videos and pictures got moved/merged with other classes, rendering the current hooks unusable. It means that not only the method's names have to be updated, but how the saving and sharing works. As an example, notice how there is a separate image/video rendering class, but from 9.6.0.0+ they no longer exist, same for the Snapbryo class, etc. Saving is still possible, but has to be looked into how their new way of processing the images and videos works.

A viewable option is to place printstacktraces to the method which sets the view to the image/video, this way we will have our new rendering class and methods for images and videos. Saving from there is pretty straight forward.

As far as sharing is concerned, we need to find the new method and class, which holds our taken image/video. If we have it, then we can easily add our desired image/video to it.

The above is just theory, but could work. ATM I cannot look further into it, due to finals, but after they are over Snapprefs will be updated.

**Comment by n1-d** [comment]
I personally will look into this and am looking forward to update this beautiful app
