### ISSUE TITLE
How is it comming along?

### ISSUE THREAD

**Issue by LakuuPiipu** [marzika/Snapprefs#66]
Would be nice if you had some sort of checklist, like on the stream but somewhere so there is a way of tracking the development.

**Comment by ItzTrevorr** [comment]
There is a way of tracking the development for here. You can enable email notifications by subscribing to marzika. Also, you can see the latest commits by going to the snapprefs page and looking at the top of the files. But i do agree with there being a better way of tracking the developmen txD.

**Comment by blacksteve13** [comment]
Its never a good idea to ask for ETA on any type of development. This is the exact reason why the xda page got shut down. The best thing to do is wait. The newest update will probably be in may because the dev is a lot more active and probably has a lot more time after dealing with what ever he was in life. Just be patient

**Comment by marzika** [comment]
We have a provate Trello Board listing ideas where we assign tasks to ourselves. I am sorry, but that will not be released. Mostly visual stuff has to be done to adapt to the new design, like the Visual Filter store and regular Filter store.
