### ISSUE TITLE
Version 1.6.5

### ISSUE THREAD

**Issue by hakankocyigit** [marzika/Snapprefs#71]
Sending pictures from the gallery to the story? How to do?

**Comment by Laamapalmu** [comment]
Go to gallery, choose a photo and in the top right corner or wherever you can share the photo, choose Snapprefs. Then it will open snapchat and give a warning box, click ok and then press your back button, after that take a photo in snapchat  and the photo from gallery should apper on the screen. Then you can send it or share it in the mystory normally, after that you need to close snapchat before taking other pictures because otherwise it will always show the picture from gallery.

**Comment by hakankocyigit** [comment]
Thank you very much :)

**Comment by marzika** [comment]
The issue page of Github is made for reporting issues, not for asking stuff that has been answered countless times in the XDA thread.
