### ISSUE TITLE
Did you remove rainbow text?

### ISSUE THREAD

**Issue by LakuuPiipu** [marzika/Snapprefs#72]
Compiled the app to check everything out, noticed there isnt an option for rainbow text,
Did you remove that or? And i didnt get the new things like font or any of thoose to work for me. Live blocking works and the new sharing button works´, and the open settings from snapchat app works.

**Comment by marzika** [comment]
I have removed that since you can do real rainbow coloring with the new gradient option. Every new feature is working perfectly as it has been tested numerous times across multiple devies and android versions.

**Comment by alexhulbert** [comment]
Hate to jump ship here, but what version of SnapChat is the current HEAD built for? I'd like to screw around with the source and whatnot as well.

**Comment by marzika** [comment]
The latest supported version is always indicated in the Obfuscator.java as a Constant. (Right now it is 9.21.1.0)

**Comment by LakuuPiipu** [comment]
@marzika Then i have to done something wrong when compiling, i recorded the error!
https://vid.me/uSQK
As you can see, it only happens when pressing the new gradient or font things.

**Comment by marzika** [comment]
I need a logcat of the issue.

2016-05-03 14:23 GMT+02:00 LakuuPiipu notifications@github.com:

**Comment by LakuuPiipu** [comment]
@marzika 
http://pastebin.com/JvLhmD0j

But i really do think it might be cause of me not compiling right or something like that but anyhow.

**Comment by marzika** [comment]
The Xposed log isn't the same as a logcat, I asked for a logcat of the crash.

**Comment by TehMerkMods** [comment]
http://tehmerkmods.xyz/Android/Random%20Files/S4Problem.txt

Here is a logcat of my issue not sure if it displays what the issue is but i get the same as him, When pressing Gradient i crash

**Comment by marzika** [comment]
Fixed. Let me know if the crash still happens after this commit.
https://github.com/marzika/Snapprefs/commit/e2c825199f67b86ed15943c5721caec0e9153600

**Comment by AmineI** [comment]
While I totally understand why you removed it, I think these are two different features : Rainbow is random, the gradient is not, but the real difference is that rainbow will color each letter separately, whereas the gradient don't, and don't even take the character number into account, so that it won't even be visible in a caption of 3 letters. At least, I guess the gradient should take the number of characters into account so that the last character is the end of the gradient if it's a one-line caption?
 +,  on my phone it stills crashes, but only with the "background transparency" option.

**Comment by marzika** [comment]
It's not possible to calculate the gradient that way. My change is final and I will not revert it, it was buggy (captions with emojis are crashing Snapchat) and rarely used.

**Comment by AmineI** [comment]
Okay, thank you anyway :) !
