### ISSUE TITLE
Crash after snap load

### ISSUE THREAD

**Issue by ahmedtsadek** [marzika/Snapprefs#86]
after viewing one snap it crashes
here are both logcat and xposed log
logcat : http://pastebin.com/wVtJ3tCy
xposed log: http://pastebin.com/TAmKkmCR

**Comment by ahmedtsadek** [comment]
And one more error at xposed log https://mega.nz/#!3d01SAzT!7lBC9gQiSm6w5SMiy4SiW2sgK4ARwKrthtrXNiWZczM

**Comment by marzika** [comment]
Please disable every other module (mainly xRenamer) apart from Snapprefs and retake both the Xposed log and Logcat.

**Comment by ahmedtsadek** [comment]
Xposed log after disabling all of modules except snapprefs and reboot https://mega.nz/#!qEM1XTLC!ZJiJJBWcuv3Hztw_QyY8KjshmTsMZL4CSJL9pUV4ISg

Catlog https://mega.nz/#!SclySa7Z!WtS-Q6yF9zen3oljG_wDmbLv08o6225PITzpQnJwtho

**Comment by marzika** [comment]
`05-13 13:21:55.571 E/SQLiteLog(11290): (1) table FriendStorySnapTable has no column named IsUpdated
05-13 13:21:55.572 E/SQLiteDatabase(11290): Error inserting StorySnapId=addmeandpay~1463053032079 ExpirationTimestamp=1463139432215 MediaId=6411352422170624 StoryFilterId= IsZipped=0 IsFailed=0 CaptionText= Status= FilterId=null DisplayTime=9999.900390625 Username=addmeandpay MediaType=1 IsSponsored=0 AdCanFollow=1 NeedsAuth=0 StoryUnlockables= IsUpdated=0 IsShared=0 Was404ResponseReceived=0 SponsoredSlugPosAndText={} Timestamp=1463053032079 MediaUrl=https://app.snapchat.com/bq/story_blob?story_id=6411352422170624&t=2&mt=1&encoding=compressed StoryId=null ViewedTimestamp=0 ScreenshotCount=0 IsViewed=1 ThumbnailUrl=https://app.snapchat.com/bq/story_thumbnail?story_id=6411352422170624&t=2&mt=1&encoding=compressed ClientId=ADDMEANDPAY~9CA187F8-D2DF-49D0-AB1D-7BCCD75E5BD5
05-13 13:21:55.572 E/SQLiteDatabase(11290): android.database.sqlite.SQLiteException: table FriendStorySnapTable has no column named IsUpdated (code 1): , while compiling: INSERT INTO FriendStorySnapTable(StorySnapId,ExpirationTimestamp,MediaId,StoryFilterId,IsZipped,IsFailed,CaptionText,Status,FilterId,DisplayTime,Username,MediaType,IsSponsored,AdCanFollow,NeedsAuth,StoryUnlockables,IsUpdated,IsShared,Was404ResponseReceived,SponsoredSlugPosAndText,Timestamp,MediaUrl,StoryId,ViewedTimestamp,ScreenshotCount,IsViewed,ThumbnailUrl,ClientId) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
05-13 13:21:55.572 E/SQLiteDatabase(11290):     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
05-13 13:21:55.572 E/SQLiteDatabase(11290):     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
05-13 13:21:55.572 E/SQLiteDatabase(11290):     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
05-13 13:21:55.572 E/SQLiteDatabase(11290):     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
05-13 13:21:55.572 E/SQLiteDatabase(11290):     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
05-13 13:21:55.572 E/SQLiteDatabase(11290):     at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
05-13 13:21:55.572 E/SQLiteDatabase(11290):     at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
05-13 13:21:55.572 E/SQLiteDatabase(11290):     at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
05-13 13:21:55.572 E/SQLiteDatabase(11290):     at com.snapchat.android.database.table.DbTable.c(SourceFile:278)
05-13 13:21:55.572 E/SQLiteDatabase(11290):     at LZ$3.run(SourceFile:2059)
05-13 13:21:55.572 E/SQLiteDatabase(11290):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-13 13:21:55.572 E/SQLiteDatabase(11290):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-13 13:21:55.572 E/SQLiteDatabase(11290):     at abj.run(SourceFile:18)
05-13 13:21:55.572 E/SQLiteDatabase(11290):     at java.lang.Thread.run(Thread.java:818)
05-13 13:21:55.656 E/SQLiteLog(11290): (1) table Chat has no column named text_format
05-13 13:21:55.667 W/System.err(11290): android.database.sqlite.SQLiteException: table Chat has no column named text_format (code 1): , while compiling: INSERT OR REPLACE  INTO Chat(has_links,is_saved_by_sender,timestamp,target_view,iter_token,is_saved_by_recipient,conversation_id,is_released_by_recipient,sender_message_state_version,ack_id,seq_num,recipient,status_text,text,send_receive_status,_id,type,text_format,released_timestamp,recipient_message_state_version,sender,link_content) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
05-13 13:21:55.669 W/System.err(11290):     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
05-13 13:21:55.670 W/System.err(11290):     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
05-13 13:21:55.671 W/System.err(11290):     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
05-13 13:21:55.671 W/System.err(11290):     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
05-13 13:21:55.671 W/System.err(11290):     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
05-13 13:21:55.671 W/System.err(11290):     at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
05-13 13:21:55.671 W/System.err(11290):     at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
05-13 13:21:55.671 W/System.err(11290):     at com.snapchat.android.database.table.ChatTable.a(SourceFile:257)
05-13 13:21:55.671 W/System.err(11290):     at com.snapchat.android.database.table.ConversationTable.c(SourceFile:4428)
05-13 13:21:55.671 W/System.err(11290):     at LZ$3.run(SourceFile:2059)
05-13 13:21:55.671 W/System.err(11290):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-13 13:21:55.671 W/System.err(11290):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-13 13:21:55.671 W/System.err(11290):     at abj.run(SourceFile:18)
05-13 13:21:55.671 W/System.err(11290):     at java.lang.Thread.run(Thread.java:818)`

This is the error causing the crash and has nothing to do with Snapprefs, it's due to the fact that your databases aren't created correctly for your version (9.21.10). Completly reinstall Snapchat and relog into your account from scratch, do NOT restore any of your backups, create brand new ones. (Uninstall the Xposed Framework, log into Snapchat and install the Framework.)
